Repository zeta-chain/toolkit, pull requests merged in 2025-05, with the labels that each got.

#323 fix: remove help command
  packages/commands/src/accounts/index.ts
  packages/commands/src/solana/index.ts
  packages/commands/src/sui/index.ts
Labels: fix

#290 feat: evm deposit command
  package.json
  packages/client/src/evmDeposit.ts
  packages/client/src/evmDepositAndCall.ts
  packages/commands/src/evm/deposit.ts
  packages/commands/src/evm/index.ts
  packages/commands/src/index.ts
  packages/commands/src/program.ts
  types/bitcoin.types.ts
  types/shared.schema.ts
  utils/balances.ts
  utils/chains.ts
  utils/formatting.ts
  utils/gatewayEvm.ts
  yarn.lock
Labels: feat

#328 feat: accounts import command
  packages/commands/src/accounts/import.ts
  packages/commands/src/accounts/index.ts
  utils/accounts.ts
Labels: feat

#315 feat: fetch balances for Testnet 4 and Signet
  packages/client/src/getBalances.ts
  test/balances.test.ts
  types/balances.types.ts
  utils/balances.ts
Labels: feat

#316 ci: Update release-to-discord.yaml
  .github/workflows/release-to-discord.yaml
Labels: ci

#311 feat: Sui deposit command
  packages/commands/src/bitcoin/index.ts
  packages/commands/src/sui/deposit.ts
  packages/commands/src/sui/index.ts
  types/accounts.types.ts
  utils/accounts.ts
  utils/sui.ts
Labels: feat

#329 feat: evm deposit and call command
  packages/commands/src/evm/deposit.ts
  packages/commands/src/evm/depositAndCall.ts
  packages/commands/src/evm/index.ts
  types/shared.schema.ts
  utils/chains.ts
  utils/evm.command.helpers.ts
Labels: feat

#335 chore: Move the balances command inside the query namespace
  packages/commands/src/balances/index.ts
  packages/commands/src/index.ts
  packages/commands/src/program.ts
  packages/commands/src/query/balances.ts
  packages/commands/src/query/index.ts
Labels: chore

#337 feat: fetch Sui balances and correctly import `suiprivkey1` keys
  packages/client/src/getBalances.ts
  packages/commands/src/query/balances.ts
  types/balances.types.ts
  utils/accounts.ts
  utils/addressResolver.ts
  utils/balances.ts
  utils/formatting.ts
Labels: feat

#338 feat: Zetachain call command
  packages/client/src/zetachainCall.ts
  packages/commands/src/evm/call.ts
  packages/commands/src/evm/deposit.ts
  packages/commands/src/evm/depositAndCall.ts
  packages/commands/src/index.ts
  packages/commands/src/program.ts
  packages/commands/src/zetachain/call.ts
  packages/commands/src/zetachain/index.ts
  test/toHexString.test.ts
  types/shared.schema.ts
  utils/evm.command.helpers.ts
  utils/zetachain.command.helpers.ts
Labels: feat
