Repository zeta-chain/toolkit, pull requests merged in 2025-06, with the labels that each got.

#333 feat(sui): deposit and call command
  packages/commands/src/sui/deposit.ts
  packages/commands/src/sui/depositAndCall.ts
  packages/commands/src/sui/index.ts
  utils/sui.command.helpers.ts
  utils/sui.ts
Labels: feat

#343 feat(accounts): TON support
  package.json
  packages/commands/src/accounts/import.ts
  test/exactlyOneOf.test.ts
  types/accounts.types.ts
  types/shared.schema.ts
  utils/accounts.ts
  utils/exactlyOneOf.ts
  utils/index.ts
  yarn.lock
Labels: feat

#356 feat(zetachain): display withdraw gas fee
  packages/commands/src/zetachain/call.ts
  packages/commands/src/zetachain/withdraw.ts
  packages/commands/src/zetachain/withdrawAndCall.ts
  types/contracts.types.ts
  utils/zetachain.command.helpers.ts
Labels: feat

#354 feat: CCTX tracking command
  packages/commands/src/query/cctx.ts
  packages/commands/src/query/index.ts
  types/trackCCTX.types.ts
  utils/api.ts
  utils/index.ts
  utils/sleep.ts
  utils/transactions.ts
Labels: feat

#367 chore: update protocol contracts to 13.1.0-rc3
  package.json
  packages/client/src/client.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/index.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistry.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistryErrors.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistryEvents.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/index.ts
  typechain-types/@zetachain/protocol-contracts/contracts/helpers/interfaces/index.ts
  typechain-types/@zetachain/protocol-contracts/contracts/index.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/ICoreRegistry.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVM.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVMErrors.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVMEvents.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/index.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/UniversalContract.sol/UniversalContract.ts
  typechain-types/@zetachain/protocol-contracts/contracts/zevm/interfaces/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistryErrors__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistryEvents__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/IBaseRegistry__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/interfaces/IBaseRegistry.sol/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/helpers/interfaces/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol/SystemContract__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/ICoreRegistry__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVMErrors__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVMEvents__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/IGatewayZEVM__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/IGatewayZEVM.sol/index.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/UniversalContract.sol/UniversalContract__factory.ts
  typechain-types/factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/index.ts
  typechain-types/factories/contracts/OnlySystem__factory.ts
  typechain-types/hardhat.d.ts
  typechain-types/index.ts
  yarn.lock
Labels: chore

#373 fix: add btc memo missing credential args
  utils/bitcoin.command.helpers.ts
Labels: fix
