Repository zeta-chain/toolkit, pull requests merged in 2025-04, with the labels that each got.

#297 ci: label PRs based on title
  .github/release.yml
  .github/workflows/integration.yaml
  .github/workflows/pr-labeler.yaml
  .github/workflows/semantic-pr.yaml
  scripts/integration.sh
Labels: ci

#305 fix(utils): import paths
  packages/client/src/client.ts
  packages/client/src/evmCall.ts
  packages/client/src/evmDeposit.ts
  packages/client/src/evmDepositAndCall.ts
  packages/client/src/getFees.ts
  packages/client/src/sendZeta.ts
  packages/client/src/solanaDeposit.ts
  packages/client/src/solanaDepositAndCall.ts
  packages/client/src/solanaEncode.ts
  packages/client/src/trackCCTX.ts
  packages/client/src/zetachainCall.ts
  packages/client/src/zetachainWithdraw.ts
  packages/client/src/zetachainWithdrawAndCall.ts
  utils/api.ts
Labels: fix

#307 fix: Expand tx hash validation for all supported chains
  package.json
  packages/client/src/trackCCTX.ts
  test/transactions.test.ts
  utils/transactions.ts
  yarn.lock
Labels: fix

#299 feat: create account named `default` by default
  packages/commands/src/accounts/create.ts
  types/shared.constants.ts
Labels: feat

#308 chore: export commands
  package.json
  packages/commands/src/index.ts
  packages/commands/src/program.ts
  packages/commands/src/solana/encode.ts
  packages/commands/src/solana/index.ts
Labels: chore

#285 feat: Sui encode
  packages/client/src/suiEncode.ts
  packages/commands/src/index.ts
  packages/commands/src/program.ts
  packages/commands/src/sui/encode.ts
  packages/commands/src/sui/index.ts
  test/suiEncode.test.ts
Labels: feat

#304 feat: Add Bitcoin account support
  packages/commands/src/accounts/create.ts
  packages/commands/src/accounts/delete.ts
  packages/commands/src/accounts/list.ts
  packages/commands/src/accounts/show.ts
  packages/commands/src/balances/balances.ts
  test/addressResolver.test.ts
  types/accounts.types.ts
  utils/accounts.ts
  utils/addressResolver.ts
Labels: feat

#271 feat: Uniswap v3 helpers
  contracts/SwapHelpers.sol
  package.json
  yarn.lock
Labels: feat

#280 feat: Add support for onAbort address in revert options
  packages/client/src/evmCall.ts
  packages/client/src/evmDeposit.ts
  packages/client/src/evmDepositAndCall.ts
  packages/client/src/zetachainCall.ts
  packages/client/src/zetachainWithdraw.ts
  packages/client/src/zetachainWithdrawAndCall.ts
  packages/tasks/src/evmCall.ts
  packages/tasks/src/evmDeposit.ts
  packages/tasks/src/evmDepositAndCall.ts
  packages/tasks/src/zetachainCall.ts
  packages/tasks/src/zetachainWithdraw.ts
  packages/tasks/src/zetachainWithdrawAndCall.ts
Labels: feat
